export const gymSupplements = [
  {
    id: 1,
    slug: "whey-protein-powder",
    name: "Whey Protein Powder",
    description:
      "High-quality whey protein isolate with 24g protein per serving. Great for muscle recovery and growth.",
    image: "/product1.webp",
    price: 1299,
    originalPrice: 1499,
    sale: true,
    category: "protein",
    brand: "MuscleGain",
    rating: 4.5,
    reviews: 128,
    inStock: true,
    available: true,
    sizes: ["500g", "1kg", "2kg"],
    flavors: ["Chocolate", "Vanilla", "Strawberry", "Banana"],
  },
  {
    id: 2,
    slug: "pre-workout-energy-booster",
    name: "Pre-Workout Energy Booster",
    description:
      "Advanced pre-workout formula for enhanced energy, focus and pump during intense workouts.",
    image: "/product1.webp",
    price: 899,
    originalPrice: 999,
    sale: true,
    category: "pre-workout",
    brand: "ExtremeEnergy",
    rating: 4.2,
    reviews: 86,
    inStock: true,
    available: true,
    sizes: ["300g", "500g"],
    flavors: ["Blue Raspberry", "Fruit Punch", "Watermelon"],
  },
  {
    id: 3,
    slug: "bcaa-amino-acids",
    name: "BCAA Amino Acids",
    description:
      "Branched-Chain Amino Acids supplement for improved recovery and reduced muscle soreness.",
    image: "/product1.webp",
    price: 799,
    originalPrice: 799,
    sale: false,
    category: "amino-acids",
    brand: "RecoveryPlus",
    rating: 4.0,
    reviews: 54,
    inStock: true,
    available: true,
    sizes: ["300g", "500g"],
    flavors: ["Lemon", "Orange", "Unflavored"],
  },
  {
    id: 4,
    slug: "creatine-monohydrate",
    name: "Creatine Monohydrate",
    description:
      "Pure creatine monohydrate for increased strength, power and muscle growth.",
    image: "/product1.webp",
    price: 599,
    originalPrice: 699,
    sale: true,
    category: "performance",
    brand: "PowerMax",
    rating: 4.8,
    reviews: 210,
    inStock: true,
    available: true,
    sizes: ["300g", "500g", "1kg"],
    flavors: ["Unflavored"],
  },
  {
    id: 5,
    slug: "mass-gainer-shake",
    name: "Mass Gainer Shake",
    description:
      "High-calorie mass gainer with protein, carbs and essential nutrients for weight gain.",
    image: "/product1.webp",
    price: 1499,
    originalPrice: 1599,
    sale: true,
    category: "weight-gain",
    brand: "BulkPower",
    rating: 4.1,
    reviews: 67,
    inStock: true,
    available: true,
    sizes: ["2kg", "5kg"],
    flavors: ["Chocolate", "Vanilla", "Banana"],
  },
  {
    id: 6,
    slug: "vitamin-d3-supplement",
    name: "Vitamin D3 Supplement",
    description:
      "Essential Vitamin D3 supplement for immune support and bone health.",
    image: "/product1.webp",
    price: 399,
    originalPrice: 399,
    sale: false,
    category: "vitamins",
    brand: "VitalLife",
    rating: 4.6,
    reviews: 92,
    inStock: true,
    available: true,
    sizes: ["60 capsules", "120 capsules"],
    flavors: [],
  },
  {
    id: 7,
    slug: "omega-3-fish-oil",
    name: "Omega-3 Fish Oil",
    description:
      "Pure fish oil capsules rich in Omega-3 fatty acids for heart and brain health.",
    image: "/product1.webp",
    price: 549,
    originalPrice: 649,
    sale: true,
    category: "essential-fats",
    brand: "OmegaPlus",
    rating: 4.3,
    reviews: 78,
    inStock: true,
    available: true,
    sizes: ["60 capsules", "120 capsules"],
    flavors: [],
  },
  {
    id: 8,
    slug: "casein-protein-powder",
    name: "Casein Protein Powder",
    description:
      "Slow-release casein protein for overnight recovery and sustained protein delivery.",
    image: "/product1.webp",
    price: 1199,
    originalPrice: 1199,
    sale: false,
    category: "protein",
    brand: "SlowRelease",
    rating: 4.4,
    reviews: 65,
    inStock: true,
    available: true,
    sizes: ["1kg", "2kg"],
    flavors: ["Chocolate", "Vanilla", "Strawberry"],
  },
  {
    id: 9,
    slug: "zma-supplement",
    name: "ZMA Supplement",
    description:
      "Zinc, Magnesium and Vitamin B6 formula for better recovery and sleep quality.",
    image: "/product1.webp",
    price: 699,
    originalPrice: 799,
    sale: true,
    category: "recovery",
    brand: "RecoveryPlus",
    rating: 4.2,
    reviews: 43,
    inStock: true,
    available: true,
    sizes: ["90 capsules", "180 capsules"],
    flavors: [],
  },
  {
    id: 10,
    slug: "glutamine-powder",
    name: "Glutamine Powder",
    description:
      "L-Glutamine powder for enhanced recovery and immune system support.",
    image: "/product1.webp",
    price: 649,
    originalPrice: 649,
    sale: false,
    category: "amino-acids",
    brand: "RecoveryPlus",
    rating: 4.3,
    reviews: 58,
    inStock: true,
    available: true,
    sizes: ["300g", "500g"],
    flavors: ["Unflavored"],
  },
  {
    id: 11,
    slug: "protein-bars-box",
    name: "Protein Bars Box",
    description:
      "Convenient protein bars with 20g protein per bar. Perfect for on-the-go nutrition.",
    image: "/product1.webp",
    price: 899,
    originalPrice: 999,
    sale: true,
    category: "protein-snacks",
    brand: "ProteinPlus",
    rating: 4.0,
    reviews: 112,
    inStock: true,
    available: true,
    sizes: ["12 bars", "24 bars"],
    flavors: ["Chocolate", "Vanilla", "Peanut Butter"],
  },
  {
    id: 12,
    slug: "multivitamin-complex",
    name: "Multivitamin Complex",
    description:
      "Complete multivitamin formula with essential vitamins and minerals for overall health.",
    image: "/product1.webp",
    price: 499,
    originalPrice: 599,
    sale: true,
    category: "vitamins",
    brand: "VitalLife",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    available: true,
    sizes: ["60 tablets", "120 tablets"],
    flavors: [],
  },
];

export const categories = [
  { id: "all", name: "All Products" },
  { id: "protein", name: "Protein Supplements" },
  { id: "pre-workout", name: "Pre-Workout" },
  { id: "amino-acids", name: "Amino Acids" },
  { id: "performance", name: "Performance Enhancers" },
  { id: "weight-gain", name: "Weight Gainers" },
  { id: "vitamins", name: "Vitamins & Minerals" },
  { id: "essential-fats", name: "Essential Fats" },
  { id: "recovery", name: "Recovery Supplements" },
  { id: "protein-snacks", name: "Protein Snacks" },
];

export const brands = [
  { id: "all", name: "All Brands" },
  { id: "MuscleGain", name: "MuscleGain" },
  { id: "ExtremeEnergy", name: "ExtremeEnergy" },
  { id: "RecoveryPlus", name: "RecoveryPlus" },
  { id: "PowerMax", name: "PowerMax" },
  { id: "BulkPower", name: "BulkPower" },
  { id: "VitalLife", name: "VitalLife" },
  { id: "OmegaPlus", name: "OmegaPlus" },
  { id: "SlowRelease", name: "SlowRelease" },
  { id: "ProteinPlus", name: "ProteinPlus" },
];
